version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'policeCalls'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  dataset:
    build:
      context: ./dataset
      dockerfile: Dockerfile-dataset
  web:
    depends_on:
      - db
    ports:
      - 8001:8001
    build:
      context: ./web
      dockerfile: Dockerfile-web
    command: ["adev", "runserver"]

volumes:
  postgres_data:
